### ISSUE TITLE
Error when reproducing your codes

### ISSUE THREAD

**Issue by GuangChen2016** [philipperemy/tensorflow-phased-lstm#1]
@philipperemy Hello, I have downloaded your codes, and after I have installed the requirements, I got this error. Do I miss something? Thank you.
![uso67rh c3viy61dl9 gvr](https://cloud.githubusercontent.com/assets/23181283/21513409/1cb56e9e-ccf3-11e6-8499-174e7dd8875b.png)

**Comment by philipperemy** [comment]
What library of TF do you use? (CPU/GPU and version) please

**Comment by philipperemy** [comment]
It seems that TF does not take into account the registration of the MOD op gradient here:

https://github.com/philipperemy/tensorflow-phased-lstm/blob/master/phased_lstm.py#L36

So might be because your version is outdated. It works for at least for 0.12 and 0.11 from what I remember.
