### ISSUE TITLE
why leak_rate = 1.0 during test ?

### ISSUE THREAD

**Issue by etienne87** [philipperemy/tensorflow-phased-lstm#10]
```
if not training_phase:
        leak_rate = 1.0
```
in time_gate_fast inside phased_lstm.py. But in the paper they say: 
'Unless otherwise specified, the leak rate was set to
α = 0.001 during training and α = 0 during test'

**Comment by philipperemy** [comment]
@etienne87 yes you are right.

**Comment by philipperemy** [comment]
I updated the code https://github.com/philipperemy/tensorflow-phased-lstm/commit/e7975c97ab2466ad1fd78c1e241ca72aab42499e

Thanks!
