### ISSUE TITLE
Is there any code of experiment in N-MNIST?

### ISSUE THREAD

**Issue by Lucksong** [philipperemy/tensorflow-phased-lstm#13]

**Comment by philipperemy** [comment]
Can you be a bit more precise @Lucksong ?

**Comment by gd-6** [comment]
The paper relates an experiment with the N-MNIST Dataset from an event-based vision sensor. So I think the question should be : is there a code using N-MNIST dataset? If it's not the original question, I will be happy to know if there is such implementation?

**Comment by philipperemy** [comment]
@guillaumedebat you can find the official implementation there: https://github.com/dannyneil/public_plstm I haven't checked if the example you're looking for is there but I'm pretty sure it is.
