### ISSUE TITLE
Is there a PLSTM version for tf2.0?

### ISSUE THREAD

**Issue by wandli** [philipperemy/tensorflow-phased-lstm#14]
Hi,

contrib modules are no longer available in TensorFlow 2.0, even in tf.compat.v1. 

Is there a new version of PLSTM in tf2.0?

**Comment by philipperemy** [comment]
@Chrisgin10 there's nothing planned at the moment to support TF2.0 for PLSTM here.

But feel free to try and make a PR :)

I think it's still compatible up to 1.15: 

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib/rnn/PhasedLSTMCell?hl=et

**Comment by wandli** [comment]
Ok. Thanks!
BTW, do you think it's needed for a newbie to start from tf 1.x instead of 2.0? I think there are more support and material for 1.x than 2.0, but maybe 2.0 is more suitable for future learning. :)

**Comment by philipperemy** [comment]
@Chrisgin10 go for tensorflow 2.0. It's the future ;)
It's like python 2.7 vs python 3.x.
