### ISSUE TITLE
API 1.0

### ISSUE THREAD

**Issue by idrovenice** [philipperemy/tensorflow-phased-lstm#2]
Dear Philippe,

your work is amazing.
Do you have any plan to update to Tensorflow 1.0 which was just released?

Thanks.
Cheers.

**Comment by philipperemy** [comment]
@idrovenice thanks a lot!!

I don't have time at the moment. But I guess it should not be too difficult!

Maybe you can have a try and I can support if you have questions

Thanks agains!

Cheers

**Comment by philipperemy** [comment]
I might actually have some time to port it to TF 1.0!

**Comment by philipperemy** [comment]
Ok it seems to be pretty stable in terms of results.
It's in the branch called `tf10` for now.
Let me run some tests before merging to `master`.

**Comment by philipperemy** [comment]
Fixed with #3
