### ISSUE TITLE
initial state should not be plain tuple

### ISSUE THREAD

**Issue by etienne87** [philipperemy/tensorflow-phased-lstm#6]
env: 
ubuntu: 16.04
tf_version: 1.3.0
python: 2.7

When running mnist_phased_lstm.py -m BasicLSTMCell i get error:

`TypeError: The two structures don't have the same sequence type. First structure has type <type 'tuple'>, while second structure has type <class 'tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple'>.`

Easy fix, replace tuple initial_states at line 22 by:

```
initial_states = rnn.LSTMStateTuple(tf.random_normal([batch_size, hidden_size], stddev=0.1),
tf.random_normal([batch_size, hidden_size], stddev=0.1))
```

**Comment by philipperemy** [comment]
Thank you! It seems like TF 1.3.0 is not backwards compatible, as usual!

**Comment by ron-weiner** [comment]
i had the same issue for TF 1.1
i added:
"
from tensorflow.contrib import rnn
initial_states = rnn.LSTMStateTuple(tf.random_normal([batch_size, hidden_size], stddev=0.1),
tf.random_normal([batch_size, hidden_size], stddev=0.1))
"

**Comment by ron-weiner** [comment]
apparently i needed to make that change only for:
python mnist_phased_lstm.py -m BasicLSTMCell

to execute the second command, i had to use the primary definition of  initial_states.

**Comment by philipperemy** [comment]
Interesting! Anyway I strongly suggest you to upgrade to the latest version of TF :)

**Comment by philipperemy** [comment]
Same here please update to the latest tensorflow to have a working version. It's such a pity that tensorflow is so unstable when downgrading/upgrading.
