### ISSUE TITLE
module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear' - SOLVED

### ISSUE THREAD

**Issue by ron-weiner** [philipperemy/tensorflow-phased-lstm#7]
I received that error:

Traceback (most recent call last):
  File "mnist_phased_lstm.py", line 12, in <module>
    from phased_lstm import PhasedLSTMCell
  File "C:\Users\HILA\il_google_drive\code\PLSTM\tensorflow-phased-lstm\phased_lstm.py", line 13, in <module>
    _linear = rnn_cell_impl._linear
AttributeError: module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'

I'm using TF 1.1 python 3.5.
Solved by switching in the file phased_lstm.py the _linear definition.
I added:
from tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl import _linear
I removed:
_linear = rnn_cell_impl._linear

**Comment by philipperemy** [comment]
Yeah they always change where is this function...

Would you mind making a pull request with a try catch or checking the tensorflow version and make an import with if else?

Thanks!

**Comment by philipperemy** [comment]
Yes do not hesitate to upgrade to the latest version.

**Comment by ChChwang** [comment]
which version works?

**Comment by philipperemy** [comment]
@ChChwang try the latest! Should work!

**Comment by zilinly** [comment]
Help，tf1.9,module 'tensorflow.python.ops.rnn_cell_impl' has no attribute '_linear'
How to resolve ???

**Comment by philipperemy** [comment]
@zilinly try to downgrade to an older version.
